# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "aws-eks-irsa-tf-states-backup"
    dynamodb_table = "aws-eks-irsa-tf-states"
    encrypt        = true
    key            = "terraform_eks/terraform.tfstate"
    profile        = "sre-dev-1"
    region         = "eu-west-3"
  }
}
